# Generated by Django 4.2.9 on 2026-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_temp_2fa_token_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_2fa_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
