# Generated by Django 4.2.30 on 2026-06-10 20:16
"""v32 F3 — RBAC por setor (doc 08 §7.2).

O que faz: adiciona User.sectors (JSONField, default list) — lista de slugs
de setor usada pela permission HasSectorAccess. Aditiva (AddField com
default; usuários existentes ficam com [] = sem escrita em recursos
setorizados novos até o admin atribuir).

Reverse: automático do Django (remove a coluna):
    python manage.py migrate accounts 0008

Backfill: não exige. Atribuição de setores é feita pelo admin via UI.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
