# Generated by Django 4.2.30 on 2026-06-10 21:46
"""v32 F6 (doc 06): app diretoria — tabelas novas (aditivo puro).

O que faz: cria director_escalations (escalações de chamados inconclusivos)
e directory_meetings (reunião semanal estruturada) + M2M de attendees.

Reverse: automático (DROP das tabelas novas — nenhuma tabela existente é
tocada). Exige backfill: não.
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0002_alter_knowledgebasearticle_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_ref', models.CharField(blank=True, default='', help_text='Referência da semana, ex: 2026-W24', max_length=10)),
                ('agenda_review', models.JSONField(blank=True, default=dict, help_text='Checklist das 6 áreas revisadas na reunião')),
                ('decisions', models.JSONField(blank=True, default=list, help_text='Decisões e prioridades da semana')),
                ('notes', models.TextField(blank=True, help_text='Ata da reunião')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='directory_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_directory_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directory_meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DirectorEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Resumo do caso (01°)')),
                ('evidence', models.TextField(blank=True, help_text='Evidência anexada ao resumo (01°)')),
                ('decision', models.CharField(blank=True, choices=[('absorver', 'Absorver'), ('cobrar', 'Cobrar'), ('negociar', 'Negociar'), ('rejeitar', 'Rejeitar')], default='', max_length=10)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False, help_text='Decisão devolvida ao fluxo do Suporte (03°)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_escalations', to=settings.AUTH_USER_MODEL)),
                ('originating_ticket', models.ForeignKey(help_text='Chamado do Suporte com conclusao=inconclusivo', on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='support.supportticket')),
                ('raised_by', models.ForeignKey(blank=True, help_text='Null quando criada por automação (gatilho da Análise)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'director_escalations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved'], name='director_es_resolve_03a565_idx')],
            },
        ),
    ]
