# Generated by Django 4.2.9 on 2026-03-18 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_due', 'Tarefa Próxima do Prazo'), ('task_assigned', 'Tarefa Atribuída'), ('proposal_approved', 'Proposta Aprovada'), ('proposal_rejected', 'Proposta Rejeitada'), ('contract_expiring', 'Contrato Próximo do Vencimento'), ('contract_expired', 'Contrato Vencido'), ('milestone_completed', 'Marco Concluído'), ('invoice_overdue', 'Fatura Vencida'), ('invoice_paid', 'Fatura Paga'), ('ticket_assigned', 'Ticket Atribuído'), ('ticket_comment', 'Comentário no Ticket'), ('sla_warning', 'SLA Próximo de Vencer'), ('sla_breached', 'SLA Violado'), ('project_status_changed', 'Status do Projeto Alterado'), ('general', 'Geral')], default='general', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
