# Generated by Django 4.2.30 on 2026-06-10 20:56
"""v32 F5 (Produção) — schema aditivo (doc 04 §2/§3).

O que faz:
- AddField em Project: tipo, etapa_atual, recorrencia_tipo, situacao, datas
  do gatilho do Dia 0 e os 14 parâmetros do Game Plan. Todos nullable ou
  com default — sem rewrite de tabela, sem lock prolongado (expand-only).
- CreateModel: OnboardingMappingForm, ProjectDocument, ProjectAudit,
  ReUpdateCycle, WeeklyUpdate, ScheduleVersion, RecurrenceContract.
- Constraints/índices só nas tabelas NOVAS (vazias — sem custo).

Reverse: automático do Django (remove colunas/tabelas novas). Não exige
backfill — a data migration status→etapa_atual é a 0005 (PR/commit próprio,
doc 08 §4.1).
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_rename_meeting_done_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_projecttemplate_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='considerar_carnaval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='considerar_corpus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contrato_assinado_at',
            field=models.DateTimeField(blank=True, help_text='Do LegalCase(contrato) assinado', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_reuniao_apresentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_reuniao_graduacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_reuniao_validacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dia_zero',
            field=models.DateField(blank=True, help_text='Data do onboarding — só quando os 3 critérios ok', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='entrada_paga_at',
            field=models.DateTimeField(blank=True, help_text='Do Invoice da entrada (Financeiro)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='etapa_atual',
            field=models.CharField(choices=[('etapa_3_preparacao', 'Etapa 3 · Preparação'), ('etapa_4_onboarding', 'Etapa 4 · Onboarding (Dia 0)'), ('etapa_5_documentacao', 'Etapa 5 · Documentação'), ('etapa_6_validacao_doc', 'Etapa 6 · Validação da doc'), ('etapa_7_desenvolvimento', 'Etapa 7 · Desenvolvimento'), ('etapa_8_auditoria', 'Etapa 8 · Auditoria interna'), ('etapa_9_apresentacao', 'Etapa 9 · Apresentação/liberação'), ('homologacao', 'Homologação'), ('registro_entrega', 'Registro da entrega'), ('etapa_10_graduacao', 'Etapa 10 · Graduação'), ('implementacao', 'Implementação'), ('recorrencia', 'Recorrência')], default='etapa_3_preparacao', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='modo',
            field=models.CharField(choices=[('uteis', 'Dias úteis'), ('corridos', 'Dias corridos')], default='uteis', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='onboarding_realizado_at',
            field=models.DateTimeField(blank=True, help_text='Da Etapa 4', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pct_aud',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='project',
            name='pct_dev',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='project',
            name='pct_doc',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='project',
            name='peso_ent',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='peso_hom',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='project',
            name='peso_val',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='prazo_total',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='project',
            name='recorrencia_tipo',
            field=models.CharField(blank=True, choices=[('suporte_basico', 'Suporte Básico'), ('operacao_continua', 'Operação Contínua')], default='', help_text='Sub-campo da etapa recorrência (doc 04 §1 item 11)', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='reupd_fds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('em_espera', 'Em Espera'), ('cancelado', 'Cancelado')], default='ativo', help_text='Estado ortogonal — projeto em espera não perde a etapa', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='tipo',
            field=models.CharField(blank=True, choices=[('fechado', 'Fechado'), ('recorrente', 'Recorrente')], default='', help_text='Fechado ou Recorrente — vem do Comercial (doc 01)', max_length=12),
        ),
        migrations.CreateModel(
            name='WeeklyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Segunda-feira da semana')),
                ('summary', models.TextField()),
                ('pending_client_items', models.TextField(blank=True, help_text='Pendências que dependem do cliente')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reunião'), ('outro', 'Outro')], default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_weekly_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to='projects.project')),
            ],
            options={
                'db_table': 'weekly_updates',
                'ordering': ['-week_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(help_text='CronogramaParams serializados usados na geração')),
                ('game_plan', models.JSONField(help_text='GamePlan serializado (saída)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_schedule_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='projects.project')),
            ],
            options={
                'db_table': 'schedule_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReUpdateCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('client_notes', models.TextField(blank=True, help_text='Apontamentos do cliente na janela de teste')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('worked_weekends', models.IntegerField(default=0, help_text='Dias de fim de semana trabalhados (crunch)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reupdate_cycles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reupdate_cycles', to='projects.project')),
            ],
            options={
                'db_table': 'reupdate_cycles',
                'ordering': ['project', 'cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('suporte_basico', 'Suporte Básico'), ('operacao_continua', 'Operação Contínua')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=12)),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null quando criado pela automação da bifurcação', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_recurrence_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_contracts', to='sales.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_contracts', to='projects.project')),
            ],
            options={
                'db_table': 'recurrence_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_validation', 'Aguardando Validação'), ('pending_signature', 'Aguardando Assinatura'), ('signed', 'Assinada')], default='draft', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('content_url', models.URLField(blank=True, help_text='Link externo do doc (Drive/Notion/etc)')),
                ('autentique_id', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current_baseline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'db_table': 'project_documents',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('findings', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_audits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_audits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='projects.project')),
            ],
            options={
                'db_table': 'project_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingMappingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto_negocio', models.TextField(blank=True, help_text='Bloco 1 — contexto do negócio do cliente')),
                ('processos_atuais', models.TextField(blank=True, help_text='Bloco 2 — processos atuais (como opera hoje)')),
                ('dores_objetivos', models.TextField(blank=True, help_text='Bloco 3 — dores e objetivos do projeto')),
                ('sistemas_integracoes', models.TextField(blank=True, help_text='Bloco 4 — sistemas em uso e integrações')),
                ('usuarios_acessos', models.TextField(blank=True, help_text='Bloco 5 — usuários, papéis e acessos')),
                ('dados_migracao', models.TextField(blank=True, help_text='Bloco 6 — dados existentes e migração')),
                ('criterios_sucesso', models.TextField(blank=True, help_text='Bloco 7 — critérios de sucesso e medições')),
                ('extra_answers', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_onboarding_forms', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_form', to='projects.project')),
            ],
            options={
                'db_table': 'onboarding_mapping_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reupdatecycle',
            constraint=models.UniqueConstraint(fields=('project', 'cycle_number'), name='uniq_reupdate_cycle_per_project'),
        ),
        migrations.AddIndex(
            model_name='recurrencecontract',
            index=models.Index(fields=['customer', 'status'], name='recurrence__custome_4471d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_baseline', True)), fields=('project',), name='uniq_current_baseline_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_document_version_per_project'),
        ),
    ]
