# Generated by Django 4.2.30 on 2026-06-13 05:42
"""v32 ajustes (doc 09 item 08 + doc 10) — Produção. SOMENTE ADITIVO.

O que faz:
- AddField onboarding_agendado_em (nullable) ao Project — âncora provisória
  do cronograma (Visão 2). Nenhum impacto em linhas existentes.
- AlterField etapa_atual: ADICIONA o valor 'agendar' às choices (nova 1ª
  etapa) e ATUALIZA os LABELS das chaves existentes (texto só). Nenhuma chave
  renomeada/removida; max_length inalterado (30) → sem mudança de schema no
  banco. O novo default 'agendar' vale só para registros NOVOS — projetos
  existentes mantêm o etapa_atual já gravado (data migration 0007 não altera
  os já posicionados).
- CreateModel ProjectEtapaAction (checklist de ações por etapa no card —
  tabela nova).

Reverse: automático do Django (remove coluna/tabela novas; etapa_atual volta
às choices antigas — os dados ficam íntegros pois as chaves não mudaram).
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_status_to_etapa_atual_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onboarding_agendado_em',
            field=models.DateTimeField(blank=True, help_text='Reunião de Onboarding agendada (âncora provisória do cronograma)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='etapa_atual',
            field=models.CharField(choices=[('agendar', 'Agendar'), ('etapa_3_preparacao', 'Planejamento'), ('etapa_4_onboarding', 'Onboarding (Dia 0)'), ('etapa_5_documentacao', 'Documentação'), ('etapa_6_validacao_doc', 'Validação da doc'), ('etapa_7_desenvolvimento', 'Desenvolvimento'), ('etapa_8_auditoria', 'Auditoria interna'), ('etapa_9_apresentacao', 'Reunião de Apresentação'), ('homologacao', 'Janela de teste'), ('registro_entrega', 'Re-Update'), ('etapa_10_graduacao', 'Homologação'), ('implementacao', 'Concluído'), ('recorrencia', 'Implementado')], default='agendar', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectEtapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=30)),
                ('ordem', models.IntegerField(default=0)),
                ('texto', models.CharField(max_length=300)),
                ('feito', models.BooleanField(default=False)),
                ('feito_em', models.DateTimeField(blank=True, null=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_etapa_actions', to=settings.AUTH_USER_MODEL)),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_etapa_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_actions', to='projects.project')),
            ],
            options={
                'db_table': 'project_etapa_actions',
                'ordering': ['project', 'etapa', 'ordem', 'id'],
                'indexes': [models.Index(fields=['project', 'etapa'], name='project_eta_project_d11c4d_idx')],
            },
        ),
    ]
