# Generated by Django 5.1.4 on 2026-04-17 18:22

import core.managers
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', core.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cliente_nome', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], default='rascunho', max_length=16)),
                ('canvas_json', models.JSONField(blank=True, default=dict)),
                ('timeline_json', models.JSONField(blank=True, default=dict)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apresentacao',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('logo', 'Logo'), ('imagem', 'Imagem'), ('icone', 'Ícone')], max_length=16)),
                ('arquivo', models.FileField(upload_to='assets/%Y/%m/')),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('usado_em', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinkPublico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rotulo', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('senha_hash', models.CharField(blank=True, max_length=128)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.apresentacao')),
            ],
            options={
                'db_table': 'link_publico',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcessoLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('acessado_em', models.DateTimeField(auto_now_add=True)),
                ('duracao_segundos', models.PositiveIntegerField(default=0)),
                ('link_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.linkpublico')),
            ],
            options={
                'db_table': 'acesso_log',
                'ordering': ['-acessado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='apresentacao',
            index=models.Index(fields=['usuario', 'status'], name='apresentaca_usuario_a2fda0_idx'),
        ),
        migrations.AddIndex(
            model_name='apresentacao',
            index=django.contrib.postgres.indexes.GinIndex(fields=['canvas_json'], name='apres_canvas_gin'),
        ),
        migrations.AddIndex(
            model_name='apresentacao',
            index=django.contrib.postgres.indexes.GinIndex(fields=['timeline_json'], name='apres_timeline_gin'),
        ),
        migrations.AddIndex(
            model_name='linkpublico',
            index=models.Index(fields=['token'], name='link_public_token_a88c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='acessolog',
            index=models.Index(fields=['link_publico', 'acessado_em'], name='acesso_log_link_pu_c3db0a_idx'),
        ),
    ]
