# Generated by Django 4.2.30 on 2026-06-10 20:16
"""v32 F3 — app juridico (doc 02).

O que faz: cria a tabela `legal_cases` (LegalCase) — CreateModel aditivo,
tabela nova, sem impacto em dados existentes.

Reverse: automático do Django (DROP TABLE legal_cases):
    python manage.py migrate juridico zero

Backfill: não exige (entidade nova; casos nascem pelo gatilho da Coleta
de Dados ou criação manual do setor jurídico).
"""

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0033_rename_meeting_done_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_projecttemplate_phases'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('contrato', 'Contrato'), ('validacao_documento', 'Validação de Documento'), ('aditivo', 'Aditivo'), ('encerramento', 'Encerramento')], max_length=30)),
                ('status', models.CharField(choices=[('preparacao', 'Preparação'), ('envio_assinatura', 'Envio p/ Assinatura'), ('aguardando_assinatura', 'Aguardando Assinatura'), ('assinado', 'Assinado')], default='preparacao', max_length=30)),
                ('source', models.CharField(choices=[('comercial', 'Comercial'), ('producao', 'Produção'), ('cliente', 'Cliente')], default='comercial', max_length=20)),
                ('autentique_id', models.CharField(blank=True, max_length=100)),
                ('autentique_link', models.URLField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Info coletada p/ montar o documento')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='juridico/attachments/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null quando criado por automação (gatilho da Coleta de Dados)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_legal_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente único (nível 1 do CRM Jurídico)', on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='sales.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases', to='projects.project')),
            ],
            options={
                'db_table': 'legal_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process_type', 'status'], name='legal_cases_process_c34e6a_idx'), models.Index(fields=['customer', 'process_type'], name='legal_cases_custome_54616f_idx')],
            },
        ),
    ]
