# Generated by Django 4.2.30 on 2026-06-13 05:23
"""v32 ajustes (doc 09 itens 05/06/07) — app juridico. SOMENTE ADITIVO.

O que faz:
- AddField onboarding/proposal (FKs nullable, SET_NULL) ao LegalCase — vínculo
  por referência do contrato (item 05). Nullable: nenhum impacto em linhas
  existentes.
- AlterField status: ADICIONA choices (nova_solicitacao, recusado, aprovado_dev)
  para as modalidades Aditivo/Validação (itens 06/07). max_length inalterado
  (30) — sem mudança de schema no banco; nenhuma chave existente renomeada.
- CreateModel LegalCaseEvent (timeline do card — item 06). Tabela nova.

Reverse: automático do Django. Backfill: não exige (campos nullable; eventos
nascem nas transições/criação a partir desta migration).
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_add_funnel_status_choices_v32'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='onboarding',
            field=models.ForeignKey(blank=True, help_text='Coleta de Dados que originou o caso (forms do cliente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases', to='sales.clientonboarding'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Proposta aprovada vinculada (termos do contrato).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases', to='sales.proposal'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='status',
            field=models.CharField(choices=[('preparacao', 'Preparação'), ('envio_assinatura', 'Envio p/ Assinatura'), ('aguardando_assinatura', 'Aguardando Assinatura'), ('assinado', 'Assinado'), ('nova_solicitacao', 'Nova solicitação'), ('recusado', 'Recusado'), ('aprovado_dev', 'Aprovado para Desenvolvimento')], default='preparacao', max_length=30),
        ),
        migrations.CreateModel(
            name='LegalCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Caso criado'), ('status_change', 'Mudança de status'), ('modality_change', 'Mudança de modalidade'), ('signed', 'Documento assinado'), ('rejected', 'Documento recusado'), ('linked', 'Vínculo atualizado')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('from_process_type', models.CharField(blank=True, max_length=30)),
                ('to_process_type', models.CharField(blank=True, max_length=30)),
                ('autentique_link', models.URLField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='juridico.legalcase')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null quando gerado por automação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_case_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='legal_case__case_id_256ca3_idx')],
            },
        ),
    ]
