# Generated by Django 4.2.30 on 2026-06-25 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juridico', '0002_legalcase_onboarding_legalcase_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Caso criado'), ('status_change', 'Mudança de status'), ('modality_change', 'Mudança de modalidade'), ('signed', 'Documento assinado'), ('rejected', 'Documento recusado'), ('linked', 'Vínculo atualizado'), ('document', 'Documento')], max_length=30),
        ),
        migrations.CreateModel(
            name='LegalCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='Status/etapa a que a tarefa pertence', max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False, help_text='False = veio do modelo; True = avulsa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='juridico.legalcase')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_legal_case_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_case_tasks',
                'ordering': ['stage', 'order', 'id'],
                'indexes': [models.Index(fields=['case', 'stage'], name='legal_case__case_id_ac1585_idx')],
            },
        ),
    ]
