# Generated by Django 4.2.30 on 2026-06-10 20:34
"""v32 F4 (Financeiro) — campos do ciclo de pré-cadastro/liberação de cobrança.

O que faz: ADITIVA — adiciona 2 colunas em `invoices`:
- `cobranca_liberada` (bool, default False, sem lock relevante: tabela pequena)
- `precadastro_origem_id` (FK nullable para `prospects`, SET_NULL)

Reverse: `python manage.py migrate finance 0013` (Django remove as colunas;
nenhum backfill é necessário — campos novos nascem com default/null e o
código convive com os dois estados).
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_rename_meeting_done_data'),
        ('finance', '0013_paymentproviderrate_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cobranca_liberada',
            field=models.BooleanField(default=False, help_text='Cobrança liberada após assinatura do contrato (F4)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='precadastro_origem',
            field=models.ForeignKey(blank=True, help_text='Prospect que originou o pré-cadastro automático (F4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precadastro_invoices', to='sales.prospect'),
        ),
    ]
