# Generated by Django 4.2.9 on 2026-03-01 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('segment', models.CharField(choices=[('startup', 'Startup'), ('mid_size', 'Média Empresa'), ('enterprise', 'Enterprise'), ('government', 'Governo'), ('other', 'Outro')], default='mid_size', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=18)),
                ('state_registration', models.CharField(blank=True, max_length=30)),
                ('municipal_registration', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('contacts', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Indicação'), ('linkedin', 'LinkedIn'), ('event', 'Evento'), ('cold_outreach', 'Cold Outreach'), ('other', 'Outro')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado'), ('meeting', 'Reunião Agendada'), ('proposal', 'Proposta Enviada'), ('negotiation', 'Negociação'), ('won', 'Fechado - Ganho'), ('lost', 'Fechado - Perdido'), ('inactive', 'Inativo')], default='new', max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prospects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='sales.customer')),
            ],
            options={
                'db_table': 'prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('proposal_type', models.CharField(choices=[('software_dev', 'Desenvolvimento de Software'), ('maintenance', 'Manutenção'), ('consulting', 'Consultoria'), ('support', 'Suporte'), ('other', 'Outro')], max_length=20)),
                ('billing_type', models.CharField(choices=[('hourly', 'Por Hora'), ('fixed', 'Preço Fixo'), ('monthly', 'Mensal'), ('milestone', 'Por Marco')], max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('scope', models.JSONField(default=list)),
                ('deliverables', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=dict)),
                ('requirements', models.JSONField(default=list)),
                ('hours_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('viewed', 'Visualizado'), ('discussion', 'Em Discussão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='draft', max_length=20)),
                ('valid_until', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proposals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='sales.customer')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='sales.prospect')),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('software_dev', 'Desenvolvimento de Software'), ('maintenance', 'Manutenção'), ('support', 'Suporte'), ('consulting', 'Consultoria'), ('saas', 'SaaS/Assinatura'), ('other', 'Outro')], max_length=20)),
                ('billing_type', models.CharField(choices=[('hourly', 'Por Hora'), ('fixed', 'Preço Fixo'), ('monthly', 'Mensal'), ('milestone', 'Por Marco')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_days', models.IntegerField(default=30)),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_hours_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_signature', 'Pendente Assinatura'), ('active', 'Ativo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('renewed', 'Renovado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='sales.customer')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sales.proposal')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
