# Generated by Django 4.2.9 on 2026-03-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_customer_name_document_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinLossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('won', 'Ganho'), ('lost', 'Perdido')], max_length=10)),
                ('reason', models.CharField(choices=[('price', 'Preço'), ('timeline', 'Prazo'), ('competitor', 'Concorrente'), ('no_budget', 'Sem Orçamento'), ('no_fit', 'Sem Fit'), ('relationship', 'Relacionamento'), ('other', 'Outro')], max_length=50)),
                ('competitor', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='win_loss', to='sales.prospect')),
            ],
            options={
                'db_table': 'win_loss_reasons',
            },
        ),
        migrations.CreateModel(
            name='ProspectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Ligação'), ('email', 'E-mail'), ('meeting', 'Reunião'), ('whatsapp', 'WhatsApp'), ('demo', 'Demonstração'), ('linkedin', 'LinkedIn'), ('other', 'Outro')], default='call', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_activities', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.prospect')),
            ],
            options={
                'db_table': 'prospect_activities',
                'ordering': ['-date'],
            },
        ),
    ]
