# Generated by Django 4.2.9 on 2026-03-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_winlossreason_prospectactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='closer_name',
            field=models.CharField(blank=True, help_text='Nome do Closer responsável pela reunião', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='company_size',
            field=models.CharField(blank=True, choices=[('small', 'Pequena'), ('medium', 'Média'), ('large', 'Grande')], max_length=10),
        ),
        migrations.AddField(
            model_name='prospect',
            name='ebook_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='has_budget',
            field=models.BooleanField(blank=True, help_text='Budget compatível com o ticket da Inova', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='has_operation',
            field=models.BooleanField(blank=True, help_text='Tem operação rodando', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='has_urgency',
            field=models.BooleanField(blank=True, help_text='Tem urgência real — problema gera custo ou trava crescimento', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='is_decision_maker',
            field=models.BooleanField(blank=True, help_text='É tomador de decisão ou tem acesso a ele', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_attended',
            field=models.BooleanField(blank=True, help_text='Lead compareceu à reunião?', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link do Calendly / Google Meet / Zoom'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_transcript',
            field=models.TextField(blank=True, help_text='Transcrição processada da reunião comercial'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('2', 'Nível 2 — Consciente do Problema'), ('3', 'Nível 3 — Consciente da Solução'), ('4', 'Nível 4 — Consciente do Produto')], help_text='Nível do lead conforme resposta do Step 1 do quiz', max_length=1),
        ),
        migrations.AddField(
            model_name='prospect',
            name='qualification_score',
            field=models.IntegerField(default=0, help_text='Soma dos critérios atendidos (0–4). Score ≥3 = qualificado'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='quiz_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados brutos do quiz'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('internal', 'Uso Interno'), ('commercial', 'Uso Comercial')], help_text='Cenário A (uso interno) ou Cenário B (produto comercial)', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Indicação'), ('linkedin', 'LinkedIn'), ('event', 'Evento'), ('cold_outreach', 'Cold Outreach'), ('quiz', 'Quiz / Formulário'), ('other', 'Outro')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('lead_received', 'Lead Recebido'), ('qualifying', 'Em Qualificação'), ('qualified', 'Qualificado'), ('not_qualified', 'Não Qualificado'), ('scheduled', 'Agendado'), ('pre_meeting', 'Pré-Reunião'), ('no_show', 'Não Compareceu'), ('meeting_done', 'Reunião Realizada'), ('proposal_sent', 'Proposta Enviada'), ('closed', 'Fechado'), ('not_closed', 'Não Fechou'), ('follow_up', 'Em Follow-up')], default='lead_received', max_length=20),
        ),
    ]
