# Generated by Django 4.2.30 on 2026-06-10 19:04
"""v32 F2 (Comercial) — schema aditivo.

O que faz:
- AddField x6 no Prospect (project_type, meeting_2_scheduled_at, meeting_2_link,
  meeting_2_attended, tech_analysis_notes, estimated_deadline_days) — todos
  nullable ou blank com default vazio (sem rewrite/lock).
- AlterField de choices em Prospect.status e ProspectActivity.activity_type:
  choices não geram constraint no Postgres — operação só de metadado, no-op no banco.

Reverse: `python manage.py migrate sales 0031` (DropColumn dos 6 campos novos;
nenhum dado pré-existente é tocado). Não exige backfill.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_idempotency_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='estimated_deadline_days',
            field=models.IntegerField(blank=True, help_text='Prazo estimado em dias — alimenta o Game Plan (motor de cronograma)', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_2_attended',
            field=models.BooleanField(blank=True, help_text='Lead compareceu à Reunião 2?', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_2_link',
            field=models.URLField(blank=True, help_text='Link da Reunião 2 (apresentação da proposta)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='meeting_2_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='project_type',
            field=models.CharField(blank=True, choices=[('fechado', 'Fechado'), ('recorrente', 'Recorrente')], help_text='Tipo do projeto definido na Análise Técnica (fechado/recorrente)', max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='tech_analysis_notes',
            field=models.TextField(blank=True, help_text='Escopo macro + estrutura definidos pelo Dev'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Lead Recebido'), ('qualifying', 'Em Qualificação'), ('qualified', 'Qualificado'), ('meeting_invite', 'Convite para Reunião'), ('scheduled', 'Agendado'), ('pre_meeting', 'Pré-Reunião'), ('meeting_1_done', 'Reunião 1 Realizada'), ('tech_analysis', 'Análise Técnica e Proposta'), ('meeting_2_done', 'Reunião 2 Realizada'), ('proposal', 'Proposta Enviada'), ('won', 'Projeto Fechado'), ('data_collection', 'Coleta de Dados'), ('disqualified', 'Não Qualificado'), ('no_show', 'Não Compareceu'), ('follow_up', 'Em Follow-up'), ('meeting_done', 'Reunião Realizada'), ('production', 'Em Produção'), ('concluded', 'Concluído'), ('not_closed', 'Não Fechou'), ('lost', 'Perdido')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospectactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Ligação'), ('email', 'E-mail'), ('meeting', 'Reunião'), ('whatsapp', 'WhatsApp'), ('demo', 'Demonstração'), ('linkedin', 'LinkedIn'), ('other', 'Outro'), ('lead_created', 'Lead Recebido'), ('status_changed', 'Status Alterado'), ('qualified', 'Qualificado'), ('disqualified', 'Não Qualificado'), ('meeting_scheduled', 'Reunião Agendada'), ('no_show', 'Não Compareceu'), ('meeting_done', 'Reunião Realizada'), ('meeting_invite', 'Convite para Reunião'), ('meeting_1_done', 'Reunião 1 Realizada'), ('tech_analysis', 'Análise Técnica e Proposta'), ('meeting_2_done', 'Reunião 2 Realizada'), ('data_collection', 'Coleta de Dados'), ('proposal_created', 'Proposta Criada'), ('proposal_sent', 'Proposta Enviada'), ('proposal_approved', 'Proposta Aprovada'), ('proposal_rejected', 'Proposta Rejeitada'), ('won', 'Lead Fechado'), ('production', 'Em Produção'), ('concluded', 'Projeto Concluído'), ('lost', 'Lead Perdido'), ('follow_up', 'Follow-up'), ('contract_created', 'Contrato Criado')], default='call', max_length=30),
        ),
    ]
