# Generated by Django 4.2.30 on 2026-06-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_customer_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Lead Recebido'), ('qualifying', 'Em Qualificação'), ('qualified', 'Qualificado'), ('meeting_invite', 'Convite para Reunião'), ('scheduled', 'Agendado'), ('pre_meeting', 'Pré-Reunião'), ('meeting_1_done', 'Reunião 1 Realizada'), ('tech_analysis', 'Análise Técnica e Proposta'), ('meeting_2_done', 'Reunião 2 Realizada'), ('proposal', 'Proposta Enviada'), ('won', 'Projeto Fechado'), ('data_collection', 'Coleta de Dados'), ('coleta_de_dados', 'Coleta de Dados'), ('projeto_fechado', 'Projeto Fechado'), ('em_producao', 'Em Produção'), ('disqualified', 'Não Qualificado'), ('no_show', 'Não Compareceu'), ('follow_up', 'Em Follow-up'), ('meeting_done', 'Reunião Realizada'), ('production', 'Em Produção'), ('concluded', 'Concluído'), ('not_closed', 'Não Fechou'), ('lost', 'Perdido')], default='new', max_length=20),
        ),
    ]
