# Generated by Django 4.2.30 on 2026-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_add_funnel_status_choices_v32'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email',), name='uniq_customer_email_not_blank'),
        ),
    ]
