# Generated by Django 4.2 on 2026-06-19 00:00
#
# Aditiva (ERP em produção): adiciona a choice ('opt_out', 'Opt-out') ao campo
# Prospect.status, espelhando o status que o n8n já usa para leads que pediram
# para não ser mais contatados. Nenhuma choice existente é renomeada ou removida
# — esta migration apenas reaplica o CharField (mesmo max_length/default) com o
# valor novo na lista de choices. Sem mudança de schema no PostgreSQL (choices
# são validação a nível de aplicação), logo deploy seguro.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_customer_email_unique_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Lead Recebido'), ('qualifying', 'Em Qualificação'), ('qualified', 'Qualificado'), ('meeting_invite', 'Convite para Reunião'), ('scheduled', 'Agendado'), ('pre_meeting', 'Pré-Reunião'), ('meeting_1_done', 'Reunião 1 Realizada'), ('tech_analysis', 'Análise Técnica e Proposta'), ('meeting_2_done', 'Reunião 2 Realizada'), ('proposal', 'Proposta Enviada'), ('won', 'Projeto Fechado'), ('data_collection', 'Coleta de Dados'), ('coleta_de_dados', 'Coleta de Dados'), ('projeto_fechado', 'Projeto Fechado'), ('em_producao', 'Em Produção'), ('disqualified', 'Desqualificado'), ('no_show', 'Não Compareceu'), ('follow_up', 'Em Follow-up'), ('opt_out', 'Opt-out'), ('meeting_done', 'Reunião Realizada'), ('production', 'Em Produção'), ('concluded', 'Concluído'), ('not_closed', 'Não Fechou'), ('lost', 'Perdido')], default='new', max_length=20),
        ),
    ]
