# Generated by Django 4.2.30 on 2026-06-10 21:46
"""v32 F6 (doc 05): schema do realinhamento do Suporte — tudo expand-only.

O que faz:
- AddField conclusao/contexto/originating_proposal em SupportTicket (novos,
  com default/null — sem lock relevante).
- AlterField status/ticket_type: só adiciona CHOICES (choices não geram
  constraint no Postgres — zero SQL de dados).
- AlterField created_by/uploaded_by: DROP NOT NULL (canal público cria
  tickets/anexos sem usuário interno).
- AlterField TicketAttachment.file: novo validator de magic bytes
  (validação app-side, sem SQL).
- CreateModel PedidoUpdate (tabela nova).

Reverse: automático (remove campos/tabela novos; AlterFields voltam ao
estado anterior — nenhum dado é tocado). Exige backfill: não (o
realinhamento dos REGISTROS é a data migration 0004, separada).
"""
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_customer_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_knowledgebasearticle_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='conclusao',
            field=models.CharField(blank=True, choices=[('garantia', 'Garantia'), ('orcamento', 'Orçamento'), ('inconclusivo', 'Inconclusivo'), ('recorrente_corrige', 'Recorrente — Corrige')], default='', help_text='Resultado da Análise: garantia, orçamento, inconclusivo ou recorrente corrige', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='contexto',
            field=models.CharField(choices=[('homologacao', 'Homologação'), ('suporte', 'Suporte')], default='suporte', help_text='Homologação (lote no prazo) ou Suporte (SLA do plano)', max_length=15),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='originating_proposal',
            field=models.ForeignKey(blank=True, help_text='Proposta criada a partir deste chamado (conclusão=orçamento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_from_tickets', to='sales.proposal'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null quando aberto pelo cliente via canal público', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('triagem', 'Triagem'), ('analise', 'Análise'), ('correcao', 'Correção'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('open', 'Aberto (legado)'), ('in_progress', 'Em Atendimento (legado)'), ('pending_client', 'Aguardando Cliente (legado)'), ('resolved', 'Resolvido (legado)'), ('closed', 'Fechado (legado)')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('duvida', 'Dúvida'), ('mudanca', 'Mudança'), ('feature', 'Solicitação de Feature (legado)'), ('question', 'Dúvida (legado)'), ('performance', 'Performance (legado)'), ('integration', 'Integração (legado)'), ('other', 'Outro (legado)')], default='bug', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size, core.validators.validate_file_magic_bytes]),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Null quando enviado pelo cliente via canal público', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PedidoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('opened', 'Aberto'), ('promoted', 'Promovido'), ('declined', 'Recusado')], default='opened', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pedidos_update', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_update', to='sales.customer')),
                ('originating_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_update', to='support.supportticket')),
                ('prospect', models.ForeignKey(blank=True, help_text='Prospect criado ao promover (entra em tech_analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_update', to='sales.prospect')),
            ],
            options={
                'db_table': 'support_pedidos_update',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='support_ped_status_ecd922_idx'), models.Index(fields=['customer', 'status'], name='support_ped_custome_93d70a_idx')],
            },
        ),
    ]
